### ISSUE TITLE
Typo: Categorical Complexes

### ISSUE THREAD

**Issue by 0xJepsen** [Autoparallel/site#1]
In the Categorical Complexes blurb you refer to the maps between the two categorical objects A and B as 
https://github.com/Autoparallel/site/blob/19272f59e1dcee168c736483393e1a1ff43258b0/content/braindump/blurbs/categorical_complexes.md?plain=1#L12

However later in the diagram you refer to them as f_1 and f_2, the notation switch might be confusing to some.

**Comment by Autoparallel** [comment]
Oh good catch! I will fix, unless you want to.

**Comment by 0xJepsen** [comment]
I can do it!
